### ISSUE TITLE
Accordion item selector requires "a11yAccordionItem" class

### ISSUE THREAD

**Issue by tactics2** [anvk/a11yAccordion#34]
Here's my markup:

    <div class="accordion pane">
    <section>
    <h2>
      Header #1
    </h2>
    <div>
      First row content
    </div>
    </section>
    <section>
    <h2>
      Header #2
    </h2>
    <div>
      Second row content
    </div>
    </section>
    </div>

And my js:

    var myAccordion = new A11yAccordion({
    parentSelector: '.accordion',
    AccordionItemSelector: 'section',
    headerSelector: 'h2',
    hiddenAreaSelector: 'div'

But that doesn't work. The only way it functions is if I add the "a11yAccordionItem" class to each section like so:

    <section class="a11yAccordionItem">

And it has to be that specific class. Any other one won't work. 

And although it's not a bug, it would be nice to have an option to have a certain section open on load, rather than having them all collapsed by default.

Tested on Firefox 38.0.1 Mac.

**Comment by anvk** [comment]
Most likely your accordion looks odd but still works. It is due to the CSS file. I created mine to reflect the default accordion structure. If you want to use your own class names and to do something different from the example provided you will need to change CSS.

Furthermore, please see my modified *example.html* If you start clicking on the rows they will collapse and uncollapse. The only problem that the accordion will look weird but it is because CSS needs to be changed. `a11yAccordionItem` should be replaced with my new class name. In my example it is `myItem`

```html
<html>
<head>
  <link rel="stylesheet" href="dist/css/a11yAccordion.min.css" />
</head>
<body onload="load()">

  <script type="text/javascript">
    var load = function () {
      var accordion = new A11yAccordion({
        parentSelector: '#accordion1',
        hiddenLinkDescription: 'this is some row with data in first accordion',
        accordionItemSelector: '.myItem'
      });
    };
  </script>

  <div id="accordion1" class="a11yAccordion">
    <section class="myItem">
      <div class="a11yAccordionItemHeader">
        <strong>Random Information</strong>
      </div>
      <div class="a11yAccordionHideArea">
        <h2>My other content</h2>
        <p>This content is accessible by Assistive Technology and Screen Readers only when the collapsible area is visible to the user.</p>
        <a href="#">This link is also accessible only when the collapsible area is visible.</a>
      </div>
    </section>

    <section class="myItem">
      <div class="a11yAccordionItemHeader">
        <strong>Dummy Text and Controls</strong>
      </div>
      <div class="a11yAccordionHideArea">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

        <p>These controls are accessible for interaction by Assistive Technology and Screen Readers only when the collapsible area is visible to the user.</p>
        <input type='test' placeholder='Please enter some info here' style='width: 20%' /><br /><br />
        <input type='test' placeholder='Another control' />
      </div>
    </section>

    <section class="myItem">
      <div class="a11yAccordionItemHeader">
        <strong>Header with image</strong>
      </div>
      <div class="a11yAccordionHideArea">
        <img src="https://upload.wikimedia.org/wikipedia/commons/f/fe/Google_Images_Logo.png" alt="example image for the presentation purposes with a description Y U NO COLLAPSE">
      </div>
    </section>
  </div>

  <script type="text/javascript" src="js/libs/jquery-1.10.0.min.js"></script>
  <script type="text/javascript" src="dist/js/a11yAccordion-0.3.1.min.js"></script>
</body>
</html>
```

Hope it helps. If not then feel free to create a branch based on my master with a modified *example.html* which demonstrates a problem you are facing. This way it would be easier for me to help you.

**Comment by tactics2** [comment]
Hi Alexey,

I'm not using any of your css at all, just the script and markup I posted.
All of the css that controls the showing and hiding of each section is
written inline,  so that's not the issue.

It functions fine as long as I add a class to each section. If I remove it,
the accordion is rendered completely inoperable.

Thanks,

Dean H. Hamack
Tel: (206)226-0719
Email: Dean@BushidoDesigns.net

From:  Alexey Novak <notifications@github.com>
Reply-To:  anvk/a11yAccordion
<reply+007371fa52c2d6aec4d4e8f88724fed9bcf1fbe8474a259c92cf000000011174ae229
2a169ce04b0671f@reply.github.com>
Date:  Wednesday, May 20, 2015 1:18 PM
To:  anvk/a11yAccordion <a11yAccordion@noreply.github.com>
Cc:  Dean Hamack <dean@bushidodesigns.net>
Subject:  Re: [a11yAccordion] Accordion item selector requires
"a11yAccordionItem" class (#34)


Most likely your accordion looks odd but still works. It is due to the CSS
file. I created mine to reflect the default accordion structure. If you want
to use your own class names and to do something different from the example
provided you will need to change CSS.

Furthermore, please see my modified example.html If you start clicking on
the rows they will collapse and uncollapse. The only problem that the
accordion will look weird but it is because CSS needs to be changed.
a11yAccordionItem should be replaced with my new class name. In my example
it is myItem

<html>
<head>
  <link rel="stylesheet" href="dist/css/a11yAccordion.min.css" />
</head>
<body onload="load()">

  <script type="text/javascript">    var load = function () {      var
accordion = new A11yAccordion({        parentSelector: '#accordion1',
hiddenLinkDescription: 'this is some row with data in first accordion',
accordionItemSelector: '.myItem'      });    };  </script>

  <div id="accordion1" class="a11yAccordion">
    <section class="myItem">
      <div class="a11yAccordionItemHeader">
        <strong>Random Information</strong>
      </div>
      <div class="a11yAccordionHideArea">
        <h2>My other content</h2>
        <p>This content is accessible by Assistive Technology and Screen
Readers only when the collapsible area is visible to the user.</p>
        <a href="#">This link is also accessible only when the collapsible
area is visible.</a>
      </div>
    </section>

    <section class="myItem">
      <div class="a11yAccordionItemHeader">
        <strong>Dummy Text and Controls</strong>
      </div>
      <div class="a11yAccordionHideArea">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
commodo consequat.

        <p>These controls are accessible for interaction by Assistive
Technology and Screen Readers only when the collapsible area is visible to
the user.</p>
        <input type='test' placeholder='Please enter some info here'
style='width: 20%' /><br /><br />
        <input type='test' placeholder='Another control' />
      </div>
    </section>

    <section class="myItem">
      <div class="a11yAccordionItemHeader">
        <strong>Header with image</strong>
      </div>
      <div class="a11yAccordionHideArea">
        <img 
src="https://upload.wikimedia.org/wikipedia/commons/f/fe/Google_Images_Logo.
png" alt="example image for the presentation purposes with a description Y U
NO COLLAPSE">
      </div>
    </section>
  </div>

  <script type="text/javascript"
src="js/libs/jquery-1.10.0.min.js"></script>  <script type="text/javascript"
src="dist/js/a11yAccordion-0.3.1.min.js"></script>
</body>
</html>
Hope it helps. If not then feel free to create a branch based on my master
with a modified example.html which demonstrates a problem you are facing.
This way it would be easier for me to help you.


Reply to this email directly or view it on GitHub
<https://github.com/anvk/a11yAccordion/issues/34#issuecomment-104023027> .

**Comment by anvk** [comment]
Try this then. I re-created your structure and it works fine for me both in FireFox and Chrome.

Replace *example.html* with the following code:

```html
<html>
<head>
  <link rel="stylesheet" href="dist/css/a11yAccordion.min.css" />
</head>
<body onload="load()">

  <script type="text/javascript">
    var load = function () {
      var accordion = new A11yAccordion({
        parentSelector: '.accordion',
        accordionItemSelector: 'section',
        headerSelector: 'h2',
        hiddenAreaSelector: 'div'
      });
    };
  </script>

  <div class="accordion pane">
    <section>
      <h2>
        Header #1
      </h2>
      <div>
        First row content
      </div>
    </section>

    <section>
      <h2>
        Header #2
      </h2>
      <div>
        Second row content
      </div>
    </section>
  </div>

  <script type="text/javascript" src="js/libs/jquery-1.10.0.min.js"></script>
  <script type="text/javascript" src="dist/js/a11yAccordion-0.3.1.min.js"></script>
</body>
</html>
```

**Comment by tactics2** [comment]
That works, as long as you wrap the script it in the load function. If you
just use this, it doesn't:

 var accordion = new A11yAccordion({
        parentSelector: '.accordion',
        accordionItemSelector: 'section',
        headerSelector: 'h2',
        hiddenAreaSelector: 'div'
      });

Dean H. Hamack
Tel: (206)226-0719
Email: Dean@BushidoDesigns.net

From:  Alexey Novak <notifications@github.com>
Reply-To:  anvk/a11yAccordion
<reply+007371fab9b582812759260a28cdcbf2c424db64cb79c70392cf000000011174b34c9
2a169ce04b0671f@reply.github.com>
Date:  Wednesday, May 20, 2015 1:40 PM
To:  anvk/a11yAccordion <a11yAccordion@noreply.github.com>
Cc:  Dean Hamack <dean@bushidodesigns.net>
Subject:  Re: [a11yAccordion] Accordion item selector requires
"a11yAccordionItem" class (#34)


Try this then. I re-created your structure and it works fine for me both in
FireFox and Chrome.

Replace example.html with the following code:

<html>
<head>
  <link rel="stylesheet" href="dist/css/a11yAccordion.min.css" />
</head>
<body onload="load()">

  <script type="text/javascript">    var load = function () {      var
accordion = new A11yAccordion({        parentSelector: '.accordion',
accordionItemSelector: 'section',        headerSelector: 'h2',
hiddenAreaSelector: 'div'      });    };  </script>

  <div class="accordion pane">
    <section>
      <h2>
        Header #1
      </h2>
      <div>
        First row content
      </div>
    </section>

    <section>
      <h2>
        Header #2
      </h2>
      <div>
        Second row content
      </div>
    </section>
  </div>

  <script type="text/javascript"
src="js/libs/jquery-1.10.0.min.js"></script>  <script type="text/javascript"
src="dist/js/a11yAccordion-0.3.1.min.js"></script>
</body>
</html>

Reply to this email directly or view it on GitHub
<https://github.com/anvk/a11yAccordion/issues/34#issuecomment-104031624> .

**Comment by anvk** [comment]
I'm glad it worked for you and there is no issue with accordion.
Will close this issue.
