### ISSUE TITLE
Row item at start

### ISSUE THREAD

**Issue by Grahamhoare** [anvk/a11yAccordion#35]
Hi,
Not sure if I should ask here but - I see in your example you have one item open at the start, how is this done? I'd like ideally to use the showOne - false, but have the first item in the accordion open to start with?
many thanks Graham

**Comment by anvk** [comment]
Hi @Grahamhoare 

That is a good question.

If you take a look at the `example.html` you will see the following code:

``` javascript
     // [1]
      var accordion = new A11yAccordion({
        parentSelector: '#accordion1',
        hiddenLinkDescription: 'this is some row with data in first accordion'
      });
      
      accordion.uncollapseRow(1); // [2]
      // ...
    };
```

Basically what is happening here is the following:
1) I initialize a new accordion.
2) I programmatically show the first item at the start using accordion's API

I see that I do not have an option for default rows to be opened (something to add in the future) but you can do this through `uncollapseRow()` or `toggleRow()` https://github.com/anvk/a11yAccordion#api

Hope this helps !

**Comment by Grahamhoare** [comment]
sorry anvk, hectic weekend, thanks very much for the tip, thought it would be in there somewhere, will try out Monday :-)
much appreciated Graham
