### ISSUE TITLE
Customizable Show/Hide Icons and highlighted search results

### ISSUE THREAD

**Issue by SaraSoueidan** [anvk/a11yAccordion#37]
Hi Alexey

Thank you for replying over on Twitter. I appreciate that.

Your plugin is fantastic, and I particularly like the built-in search functionality. 

I was wondering if these three features could be added when you got the time?

1. Make the Show/Hide text replaceable with an icon (arrow up and arrow down). Preferred if the icon could be animated by rotation, so maybe add a class name or something to make this possible via CSS?

2. When the user uses searchAll to search through the closed tabs, it would be great if the tab that contains the search word automatically opens to show that the word is available inside the tab, not in the headline.

3. Related to (2): highlight the keyword in the search results. So the user would get instant feedback if the keyword is available in the heading, and also see the open panel if the keyword is available inside the panel.

Thank you for taking the time to consider this.

**Comment by anvk** [comment]
@SaraSoueidan I created changes you asked for in branch `issue36`. I have not merged to master yet since missing tests, some more refactoring and proper README documentation.
But if you get the branch and check one of the examples you will see functionality you were asking for.

**Comment by SaraSoueidan** [comment]
@anvk That was fast! Thanks so much Alexey! 👏🏻

**Comment by anvk** [comment]
You can start using this branch for now and let me know here if you find any problems with it. In the meantime I will try to merge this code into master. Just need to add tests and finish refactoring I have started.

**Comment by anvk** [comment]
Fixed in 0.4.0
