### ISSUE TITLE
Auto height setting

### ISSUE THREAD

**Issue by Grahamhoare** [anvk/a11yAccordion#43]
Hi,
I have an issue where the height of the accordion area is calculated by css before the  A11lyaccordian expanded items have loaded. When the accordion then loads (expanded) it slides down over the footer, or if I open one of the accordion items it slides down over the footer. So the problem is that my css around the accordion isn't adjusting to the new heights given. esp on page load. Jquery accordion has an autoHeight: setting, does this have something similar?. When the browser window is moved the footer springs to the right place instantly, I'm sure this is Allyaccordion and not the surrounding css.
What I've noticed is that A11lyaccordian is giving the surrounding item a height before it is expanded.
Screen shot attached
Tnx Graham
![a11lyaccordian-height-issue](https://cloud.githubusercontent.com/assets/2083871/25901001/4563f0ba-358d-11e7-84c9-bbb79ba22f2c.jpg)

**Comment by anvk** [comment]
For one there is absolutely no code or CSS or LESS around heights. It is pretty much HTML controls which become visible and invisible to the human eye.

Secondly, I do not have anything like autoHeight. This control relies only on styling CSS (which is generated through LESS). It means that there is nothing fancy or nothing is auto-calculated. But on the good side - accordion's code is lean and it is fully up to developer/user to modify or add any CSS rules to make it fit the page/use case.

Lastly, It does sound like you need to do some debugging around the website to see why the container element which has accordion allows its children elements to appear outside of its bounds. This is very common problem when container is not responsive and does not stretch its size to the size of its content/children.

In your code example you have a screenshot where you show height property inside the `element.style` of the accordion. If you do a quick scan through my source code https://github.com/anvk/a11yAccordion/blob/master/src/a11yAccordion.js you will see that there is nothing related to the accordion's height. As well as in Demo page you won't find it either.

I believe you summed up your problem very well in the following sentence:

> So the problem is that my css around the accordion isn't adjusting to the new heights given. esp on page load.
