### ISSUE TITLE
How can we give different hiddenlinkDescriptions for each a11yAccordionItem in AccordionSection

### ISSUE THREAD

**Issue by AshokDev1** [anvk/a11yAccordion#45]

**Comment by anvk** [comment]
No in the current setup. Do you need this feature? It is the first time I hear such a request.

It is a bit tricky to implement. There are no arrays or data which is used to iterate over for me to make `hiddenlinkDescription` to be a callback. It is very tricky to implement....

**Comment by AshokDev1** [comment]
I should explain my situation a little clearer to you
here's the screen i'm using the A11yAccordion, here all the accordions are different from one other having different data, our application is trying to be JAWS accessible. 
![image](https://user-images.githubusercontent.com/29803376/27872636-00dee3ba-616f-11e7-868a-d9860a03ab66.png)
Our aim was to get the accordions shown up in the JAWS Heading list as links, so that they can be accessible and control showing and hiding of them. In order to get the each accordion their own description i had to create and initialize all these accordions separately 
![image](https://user-images.githubusercontent.com/29803376/27873248-f8c80dee-6170-11e7-91f3-bebd61e85547.png)
It would be easier if i can just give hiddenlinkDescriptions to each Accordionitem in Accordion Section.

**Comment by anvk** [comment]
Correct me if I'm wrong but it looks like 1 accordion with 6 accordion items. You **can** set `hiddenLinkDescription` for different accordions. But you **cannot** set different `hiddenLinkDescription` for different items **within** the same accordion.

**Comment by anvk** [comment]
Let me see what I can do for you

**Comment by anvk** [comment]
@AshokDev1 I made some changes in a11yAccordion. Basically you can overwrite `hiddenLinkDescription` for the sections you need a custom text instead of a generic one.

[How to set a custom hiddenLinkDescription on a specific row](https://github.com/anvk/a11yAccordion#how-to-set-a-custom-hiddenlinkdescription-on-a-specific-row)

Is it what you are looking for?
